package com.pricehawk.common.event;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.time.Instant;

@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class ScrapeRequestEvent {

    /** UUID generated by Catalog Service — dùng để track job status */
    private String jobId;

    private String url;

    /** Nullable — anonymous users có thể trigger scrape */
    private String userId;

    @Builder.Default
    private Instant requestedAt = Instant.now();
}
